title: "SWeetJelly Studio"
email: sweetjellystudio@gmail.com
timezone: UTC+9
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: SweetJelly
paginate: 30
disqus: 'www-sweetjellystudio-com'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:

# Authors
authors:
  sal:
    name: SWeetJelly
    display_name: SWeetJelly
    avatar: 'assets/images/SweetJelly.png'
    email: sweetjellystudio@gmail.com
    web: https://www.sweetjellystudio.com/about/
    description: "Thank you for coming. This is SWeetJelly Game Dev Studio"

# Social
social:
  instagram:
  facebook:
  kakaotalk:
  discord:
  youtube:

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-latex