title: "SWeetJelly Studio"
email: sweetjellystudio@gmail.com
timezone: UTC+9
baseurl: 'https://www.sweetjellystudio.com'
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: SweetJelly
paginate: 30
disqus: 'www-sweetjellystudio-com'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:

# Authors
authors:
  sal:
    name: SWeetJelly
    display_name: SWeetJelly
    avatar: 'assets/images/sal.png'
    email: sweetjellystudio@gmail.com
    web: https://www.sweetjellystudio.com/about/
    description: "Thank you for coming. This is SWeetJelly Game Dev Studio"
#  john:
#    name: John
#    display_name: John
#    avatar: 'assets/images/john.png'
#    email: wowthemesnet@gmail.com
#    web: https://www.wowthemes.net/category/jekyll-themes/
#    twitter: https://twitter.com/wowthemesnet
#    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram:
  facebook:
  kakaotalk:
  discord:

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-latex